/* Embeds every root-level .html page into a single Cloudflare Worker.
   Run automatically by Cloudflare's build step: npm run build */
const fs = require("fs");
const path = require("path");

const ROUTES = {
  "/": "index.html",
  "/index.html": "index.html",
  "/enroll": "index.html",
  "/faq": "faq.html",
  "/faq.html": "faq.html"
};

const pages = {};
for (const file of new Set(Object.values(ROUTES))) {
  const p = path.join(__dirname, file);
  if (!fs.existsSync(p)) { console.error("MISSING PAGE:", file); process.exit(1); }
  pages[file] = fs.readFileSync(p).toString("base64");
  console.log("embedded", file, "(" + Math.round(fs.statSync(p).size / 1024) + " KB)");
}

const worker = `// GENERATED by build.js — do not edit directly
const PAGES = ${JSON.stringify(pages)};
const ROUTES = ${JSON.stringify(ROUTES)};
function decode(b64){
  const bin = atob(b64);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  return new TextDecoder().decode(bytes);
}
export default {
  async fetch(request) {
    const url = new URL(request.url);
    const file = ROUTES[url.pathname] || ROUTES[url.pathname.replace(/\\/$/, "")] || null;
    if (!file) return new Response("Not found", { status: 404 });
    return new Response(decode(PAGES[file]), {
      headers: { "content-type": "text/html;charset=UTF-8", "cache-control": "no-cache" }
    });
  }
};
`;

fs.mkdirSync(path.join(__dirname, "dist"), { recursive: true });
fs.writeFileSync(path.join(__dirname, "dist", "worker.js"), worker);
console.log("wrote dist/worker.js");
